# Generated by Django 4.1.1 on 2022-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', 'Date'), ('', 'DateTime'), ('', 'Time'), ('', 'Decimal'), ('', 'Char'), ('', 'Intager'), ('', '')], max_length=127)),
            ],
        ),
    ]
